name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-18.04
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ruby_en_glish_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 4s
          --health-retries 4
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4 
          bundler-cache: true
      - name: Build and run tests
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/ruby_en_glish_test
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          RUBY_EN_GLISH_DATABASE_PASSWORD: postgres
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler -v  2.2.23
          bundle install --jobs 4 --retry 3
          bundle exec rails db:prepare
          bundle exec rails spec
  # https://github.com/AkhileshNS/heroku-deploy
  deploy:
    runs-on: ubuntu-18.04
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL_ADDRESS}}
          healthcheck: "https://${{secrets.HEROKU_APP_NAME}}.herokuapp.com/healthcheck"
          checkstring: "OK"
          delay: 10

      


